(async () => {
  const base = 'http://localhost:3001';
  const adminToken = Buffer.from('admin:Admin@123').toString('base64');

  console.log('ADMIN TOKEN:', adminToken);

  try {
    console.log('\n1) Creating ticket...');
    const createRes = await fetch(`${base}/api/tickets`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        requestor_name: 'Smoke Tester',
        requestor_email: 'smoke+tester@example.com',
        department: 'IT Support',
        contact_type: 'Web',
        priority: 'Low',
        short_description: 'Smoke test ticket',
        description: 'This is a test ticket generated by smoke test.'
      }),
    });
    const createJson = await createRes.json();
    console.log('Create status:', createRes.status);
    console.log(JSON.stringify(createJson, null, 2));

    const ticketId = createJson?.ticket?.id;
    const ticketNumber = createJson?.ticket?.ticket_number;
    if (!ticketId) throw new Error('Ticket ID missing from create response');

    console.log(`\nTicket ID: ${ticketId}`);

    console.log('\n2) Posting admin comment...');
    const postCommentRes = await fetch(`${base}/api/ticket_comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-admin-token': adminToken },
      body: JSON.stringify({ ticket_id: ticketId, sender: 'Admin', message: 'Hello user, we received your request (smoke test).' }),
    });
    const postCommentJson = await postCommentRes.json();
    console.log('Post comment status:', postCommentRes.status);
    console.log(JSON.stringify(postCommentJson, null, 2));

    console.log('\n3) Fetching comments...');
    const commentsRes = await fetch(`${base}/api/ticket_comments?ticket_id=${ticketId}`);
    const commentsJson = await commentsRes.json();
    console.log('Comments status:', commentsRes.status);
    console.log(JSON.stringify(commentsJson, null, 2));

    console.log('\n4) Updating ticket status to Completed...');
    const updateRes = await fetch(`${base}/api/tickets`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', 'x-admin-token': adminToken },
      body: JSON.stringify({ id: ticketId, status: 'Completed' }),
    });
    const updateJson = await updateRes.json();
    console.log('Update status:', updateRes.status);
    console.log(JSON.stringify(updateJson, null, 2));

    console.log('\nSmoke test completed.');
  } catch (err) {
    console.error('Smoke test error:', err);
    process.exitCode = 1;
  }
})();
